churchm/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from churchm import db
from churchm.forms import UserCreateForm, UserLoginForm, MemberCreateForm
from churchm.models import User, Member

from datetime import datetime
import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data, password=generate_password_hash(form.password1.data))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)

    return wrapped_view


@bp.route('/add/', methods=('GET', 'POST'))
@login_required
def add():
    form = MemberCreateForm()

    if request.method == 'POST' and form.validate_on_submit():
        print("add access")
        member = Member(name=form.memberName.data, age=form.memberAge.data, sex=form.memberSex.data,
                        birthday=form.memberBirthday.data, contact1=form.memberContact1.data,
                        contact2=form.memberContact2.data, contact3=form.memberContact3.data,
                        address=form.memberAddress.data, job=form.memberJob.data,
                        email=form.memberEmail.data, baptism=form.memberBaptism.data,
                        marriage=form.memberMarriage.data, prevChurch=form.memberPrevChurch.data,
                        create_date=datetime.now(), modify_date=form.memberModify_date.data
                        )
        db.session.add(member)
        db.session.commit()
        return redirect(url_for('member._list'))

    return render_template('auth/add.html', form=form)

churchm/views/member_views.py
from flask import Blueprint, render_template, redirect, url_for, request, g, flash

from ..forms import MemberCreateForm
from churchm.models import Member
from churchm import db
from churchm.views.auth_views import login_required
from datetime import datetime

bp = Blueprint('member', __name__, url_prefix='/member')


# 교인 리스트
@bp.route('/list/')
@login_required
def _list():
    member_list = Member.query.order_by(Member.create_date.desc())
    return render_template('member/member_list.html', member_list=member_list)


# 교인 상세 조회
@bp.route('/detail/<int:member_id>/')
@login_required
def detail(member_id):
    form = MemberCreateForm()
    member = Member.query.get_or_404(member_id)
    return render_template('member/member_detail.html', member=member, form=form)


# 교인 정보 수정
@bp.route('/modify/<int:member_id>/', methods=('GET', 'POST'))
@login_required
def modify(member_id):
    member = Member.query.get_or_404(member_id)
    if g.user.grade != 'manager':
        flash('수정권한이 없습니다.')
        return redirect(url_for('member.detail', member_id=member_id))

    if request.method == 'POST':
        form = MemberCreateForm()
        if form.validate_on_submit():
            form.populate_obj(member)
            member.modify_date = datetime.now()
            db.session.commit()
            print(form.memberName.validators)
            print(member.name)
            print('no way')
            return redirect(url_for('member.detail', member_id=member_id))
    else:
        form = MemberCreateForm(obj=member)

    return render_template('member/member_modify.html', form=form, member=member)


# 교인 정보 삭제
@bp.route('/delete/<int:member_id>/')
@login_required
def delete(member_id):
    member = Member.query.get_or_404(member_id)
    if g.user.grade != "manager":
        print("접근권한 없음")
        print(g.user.grade)
        flash('삭제권한이 없습니다')
        return redirect(url_for('member.detail', member_id=member_id))
    db.session.delete(member)
    db.session.commit()
    print("commit ok")
    return redirect(url_for('member._list'))

churchm/templates/member/member_detail.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-3 mb-3 p-1;">
    <form method="post" class="post-form">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}

        <div style="font-family: 빙그레 메로나체" align="center">
            <!--            <div class="col-sm-12 col-md-12 col-lg-12 mb-1">-->
            <div>
                <div style="overflow-x:auto;" id="content" class="border-top border-secondary">
                    <div class="content_block">
                        <h4 class="border-bottom p-2" align="center">현재 <b>{{ g.user.username }}</b>님께서 <b>{{
                            member.name}}</b>님을 조회중입니다.</h4>

                        <!--                        성도님의 사진이 들어가는 자리-->
                        <div class="square" align="center">
                            <img src="/static/pigeon.png">
                        </div>

                        <div class="mt-1" style="border: 1px solid skyblue;">

                            <table class="tbClass" style="border-collapse: separate; border-spacing: 6px;">

                                <tr>
                                    <td colspan="2"> 이름 : {{ member.name }}</td>
                                    <td colspan="2"> 나이 : {{ member.age }}</td>
                                    <td colspan="2"> 성별 : {{ member.sex }}</td>
                                    <td colspan="2"> 생년월일 : {{ member.birthday }}</td>
                                </tr>

                                <tr>
                                    {% if member.email %}
                                    <td colspan="4"> email : {{ member.email }}</td>
                                    {% endif %}

                                </tr>

                                <tr>
                                    {% if member.contact1 %}
                                    <td colspan="2"> 연락처 : {{ member.contact1 }}</td>
                                    {% endif %}

                                    {% if member.contact2 %}
                                    <td colspan="2"> 연락처2 : {{ member.contact2 }}</td>
                                    {% endif %}

                                    {% if member.contact3 %}
                                    <td colspan="2"> 연락처3 : {{ member.contact3 }}</td>
                                    {% endif %}
                                </tr>

                                <tr>
                                    {% if member.address %}
                                    <td colspan="4"> 주소 : {{ member.address }}</td>
                                    {% endif %}
                                </tr>

                                <tr>
                                    {% if member.job %}
                                    <td colspan="2"> 직업 : {{ member.job }}</td>
                                    {% endif %}

                                    {% if member.baptism %}
                                    <td colspan="2"> 침례여부 : {{ member.baptism }}</td>
                                    {% endif %}

                                    {% if member.marriage %}
                                    <td colspan="2"> 결혼여부 : {{ member.marriage }}</td>
                                    {% endif %}
                                </tr>


                                {% if member.prevChurch %}
                                <tr>
                                    <td colspan="3"> 이전 교회 : {{ member.prevChurch }}</td>
                                </tr>
                                {% endif %}
                            </table>
                        </div>

                        <div align="left">
                            <label class="p-1 mt-1"> 작성일자 : {{
                                member.create_date.now().date()}} </label>

                            {% if member.modify_date %}
                            <label class="p-1 mt-1"> 수정일자 : {{ member.modify_date.date()}} </label>
                            {% endif %}
                        </div>
                        <div align="center">
                            <button type="button" class="btn btn-primary"
                                    onClick="this.style.visibility='hidden'; location.href='{{ url_for('member.modify', member_id=member.id) }}'">
                                수정하기
                            </button>
                            <button type="button" class="delete btn btn-danger"
                                    data-uri="{{ url_for('member.delete', member_id=member.id) }}">삭제
                            </button>
                            <button type="button" class="btn btn-primary"
                                    onClick="this.style.visibility='hidden'; location.href='{{ url_for('member._list') }}'">
                                뒤로
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});

</script>
{% endblock %}

churchm/templates/member/member_list.html
{% extends 'base.html' %}
{% block content %}
<div style="font-family: 빙그레 메로나체; overflow-x:auto;" class="container mt-3 mb-3">
    <div>
        <div class="item" id="content" class="border-top border-secondary">
            <div>
                <div class="title border-bottom p-2 mb-2">교인 현황</div>

<!--                등록, 검색 아이콘 -->
                <div class="row justify-content-between mb-4">
                    <div class="col-6">
                        <div class="btn-group" role="group">
                            <button type="button" onclick="location.href='{{ url_for('auth.add')}} '" title="등록"
                                    class="btn btn-sm btn-secondary so active">
                                <i class="item fas fa-cross"></i></button>
                        </div>
                    </div>

<!--                    <div class="col-6 input-group input-group-sm">-->
<!--                        <input type="text" class="form-control form-control-sm kw" value=""-->
<!--                               onkeypress="return search(event)">-->
<!--                        <div class="input-group-append">-->
<!--                            <button class="btn btn-secondary" type="button" id="btn_search">-->
<!--                                <i class="fas fa-search"></i></button>-->
<!--                            </button>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>

<!--                등록된 교인 리스트-->
                <div align="center" class="table-responsive">
                    <table class="tbClass table table-striped table-hover">
                        <thead align="center">
                        <tr class="table-secondary text-dark">
                            <th>번호</th>
                            <th>이름</th>
                            <th>나이</th>
                            <th>성별</th>
                            <th>핸드폰번호</th>
                            <th>주소</th>
                            <th>작성일</th>
                        </tr>
                        </thead>

                        <tbody align="center">
                        {% if member_list %}
                        {% for member in member_list %}
                        <tr>
                            <td> {{ loop.index }}</td>
                            <td><a href="{{ url_for('member.detail', member_id=member.id)}}">{{ member.name }}</a></td>
                            <td> {{ member.age }}</td>
                            <td> {{ member.sex }}</td>
                            <td> {{ member.contact1 }}</td>
                            <td> {{ member.address }}</td>
                            <td> {{ member.create_date }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="3">등록된 교인이 없습니다.</td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

churchm/templates/member/member_modify.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="/static/placeholder.css">

<div class="item" class="container mt-3 mb-3 p-1">
    <form method="post" class="post-form">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}

        <div class="row form-group">
            <div class="col-sm-10 col-md-12 col-lg-12 mb-1">
                <div id="content" class="border-top border-secondary">
                    <div class="content_block">
                        <h4 class="border-bottom p-2" align="center">현재 <b>{{ g.user.username }}</b>님께서 수정중입니다.</h4>

                        <label for="memberName">이름</label>
                        <input type="text" class="form-control" name="memberName" id="memberName"
                               value="{{ member.name or '' }}">

                        <p></p>
                        <label for="memberAge">나이</label>
                        <input type="number" class="form-control" name="memberAge" id="memberAge"
                               value="{{ member.age or '' }}" >

                        <p></p>
                        <label for="memberSex">성별</label>
                        <input type="text" class="form-control" name="memberSex" id="memberSex"
                               value="{{ member.sex or '' }}" >

                        <p></p>
                        <label for="memberBirthday">생년월일</label>
                        <input type="date" class="form-control" name="memberBirthday" id="memberBirthday"
                               value="{{ member.birthday or '' }}" >

                        <p></p>
                        {% if member.contact1 %}
                        <label for="memberContact1">연락처 1</label>
                        <input type="text" class="form-control" name="memberContact1" id="memberContact1"
                               value="{{ member.contact1 or '' }}" >
                        {% endif %}
                        <p></p>
                        {% if member.contact2 %}
                        <label for="memberContact2">연락처 2</label>
                        <input type="text" class="form-control" name="memberContact2" id="memberContact2"
                               value="{{ member.contact2 or '' }}" >
                        {% endif %}
                        <p></p>
                        {% if member.contact3 %}
                        <label for="memberContact3">연락처 3</label>
                        <input type="text" class="form-control" name="memberContact3" id="memberContact3"
                               value="{{ member.contact3 or '' }}" >
                        {% endif %}
                        <p></p>
                        {% if member.address %}
                        <label for="memberAddress">주소</label>
                        <input type="text" class="form-control" name="memberAddress" id="memberAddress"
                               value="{{ member.address or '' }}" >
                        {% endif %}
                        <p></p>
                        {% if member.job %}
                        <label for="memberJob">직업</label>
                        <input type="text" class="form-control" name="memberJob" id="memberJob"
                               value="{{ member.job or '' }}" >
                        {% endif %}
                        <p></p>
                        {% if member.email %}
                        <label for="memberEmail">이메일</label>
                        <input type="text" class="form-control" name="memberEmail" id="memberEmail"
                               value="{{ member.email or '' }}" >
                        {% endif %}

                        <p></p>
                        <label for="memberBaptism">침례 여부</label>
                        <input type="text" class="form-control" name="memberBaptism" id="memberBaptism"
                               value="{{ member.baptism or '' }}" >

                        <p></p>
                        {% if member.marriage %}
                        <label for="memberMarriage">결혼 여부</label>
                        <input type="text" class="form-control" name="memberMarriage" id="memberMarriage"
                               value="{{ member.marriage or '' }}" >
                        {% endif %}
                        <p></p>
                        {% if member.prevChurch %}
                        <label for="memberPrevChurch">이전 교회</label>
                        <input type="text" class="form-control" name="memberPrevChurch" id="memberPrevChurch"
                               value="{{ member.prevChurch or '' }}" >
                        {% endif %}


                        <div class="mt-2" align="right">
                            <button type="submit" class="btn btn-primary"> 변경사항 저장하기 </button>
                            <button type="reset" class="btn btn-primary"> 원래대로 </button>
                            <button type="button" class="btn btn-primary" onClick="this.style.visibility='hidden'; location.href='{{ url_for('member.detail', member_id=member.id) }}'"> 취소 </button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}